const businessData = [
  {
    id: 1,
    name: "Velocity Cafe",
    isOpen: true,
    availableOffers: true,
    openingTime: "10:00",
    closingTime: "20:00",
    distance: "300m",
    rating: "4.5",
    address: "Bilkent A Building, 1st floor",
    latitude: 39.86613476149862,
    longitude: 32.74841331751553,
    offers: [
      {
        name: "Savory Box",
        price: "45 ₺",
        details: "May include these items (items will be listed here...)",
      },
      {
        name: "Sweet Box",
        price: "75 ₺",
        details: "May include these items (items will be listed here...)",
      },
      {
        name: "Pastry Box",
        price: "55 ₺",
        details: "May include these items (items will be listed here...)",
      },
    ],
  },
  {
    id: 2,
    name: "Beethoven Cafe",
    isOpen: true,
    availableOffers: true,
    openingTime: "10:00",
    closingTime: "20:00",
    distance: "350m",
    rating: "4.0",
    address: "Bilkent B Building, 2nd floor",
    latitude: 39.86883769578915,
    longitude: 32.74804230022964,
    offers: [
      {
        name: "Savory Box",
        price: "45 ₺",
        details: "May include these items (items will be listed here...)",
      },
      {
        name: "Sweet Box",
        price: "75 ₺",
        details: "May include these items (items will be listed here...)",
      },
      {
        name: "Pastry Box",
        price: "55 ₺",
        details: "May include these items (items will be listed here...)",
      },
      {
        name: "Exclusive Box",
        price: "100 ₺",
        details: "May include these items (items will be listed here...)",
      },
    ],
  },
  {
    id: 3,
    name: "Cafe Fiery",
    isOpen: true,
    availableOffers: true,
    openingTime: "10:00",
    closingTime: "20:00",
    distance: "700m",
    rating: "4.2",
    address: "Bilkent M Building, 3rd floor",
    latitude: 39.866477179576485,
    longitude: 32.74918382453541,
    offers: [
      {
        name: "Savory Box",
        price: "45 ₺",
        details: "May include these items (items will be listed here...)",
      },
      {
        name: "Sweet Box",
        price: "75 ₺",
        details: "May include these items (items will be listed here...)",
      },
      {
        name: "Pastry Box",
        price: "55 ₺",
        details: "May include these items (items will be listed here...)",
      },
      {
        name: "Very Secret Box",
        price: "200 ₺",
      },
    ],
  },
  {
    id: 4,
    name: "Rooftop Restaurant",
    isOpen: true,
    availableOffers: false,
    openingTime: "10:00",
    closingTime: "20:00",
    distance: "400m",
    rating: "4.8",
    address: "Bilkent C Building, 4th floor",
    latitude: 39.867819957719306,
    longitude: 32.74816290905867,
    offers: [],
  },
  {
    id: 5,
    name: "Tea Break",
    isOpen: false,
    availableOffers: true,
    openingTime: "10:00",
    closingTime: "20:00",
    distance: "600m",
    rating: "4.1",
    address: "Bilkent SA Building, 1st floor",
    latitude: 39.86828221142914,
    longitude: 32.74911772286561,
    offers: [
      {
        name: "Savory Box",
        price: "45 ₺",
        details: "May include these items (items will be listed here...)",
      },
    ],
  },
];

export default businessData;
