const businessData = [
  {
    id: 1,
    name: "Velocity Cafe",
    logo: require("../assets/businesslogos/logo_bakery.png"),
    isOpen: true,
    availableOffers: true,
    openingTime: "10:00",
    closingTime: "20:00",
    distance: "300m",
    rating: "4.5",
    address: "Bilkent A Building, 1st floor",
  },
  {
    id: 2,
    name: "Beethoven Cafe",
    logo: require("../assets/businesslogos/logo_coffee.png"),
    isOpen: true,
    availableOffers: true,
    openingTime: "10:00",
    closingTime: "20:00",
    distance: "350m",
    rating: "4.0",
    address: "Bilkent B Building, 2nd floor",
  },
  {
    id: 3,
    name: "Cafe Fiery",
    logo: require("../assets/businesslogos/logo_F.jpeg"),
    isOpen: true,
    availableOffers: true,
    openingTime: "10:00",
    closingTime: "20:00",
    distance: "700m",
    rating: "4.2",
    address: "Bilkent M Building, 3rd floor",
  },
  {
    id: 4,
    name: "Rooftop Restaurant",
    logo: require("../assets/businesslogos/logo_salad.png"),
    isOpen: true,
    availableOffers: false,
    openingTime: "10:00",
    closingTime: "20:00",
    distance: "400m",
    rating: "4.8",
    address: "Bilkent C Building, 4th floor",
  },
  {
    id: 5,
    name: "Tea Break",
    logo: require("../assets/businesslogos/logo_tea.jpeg"),
    isOpen: false,
    availableOffers: true,
    openingTime: "10:00",
    closingTime: "20:00",
    distance: "600m",
    rating: "4.1",
    address: "Bilkent SA Building, 1st floor",
  },
];

export default businessData;
